---
name: build

defaults:
  run:
    shell: bash

on:
  push:

jobs:
  # https://github.com/golangci/golangci-lint-action
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        # this version is not the same version as our go.mod specifies because
        # the linter fails unless it is more modern:
        #   https://github.com/golangci/golangci-lint/issues/5051#issuecomment-2386992469
        go-version: '^1.22'
        cache: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: -v
        version: v1.64.6

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'
    - run: go version
    - run: go test ./...
